# Generated by Django 4.2 on 2023-05-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, default="avatar.png", null=True, upload_to="images"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="designation",
            field=models.CharField(
                blank=True,
                choices=[("Staff", "Staff"), ("Student", "Student")],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password2",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=128,
                null=True,
                verbose_name="Confirm Password",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(
                default=None, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default=None, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default=None, max_length=255, null=True, unique=True
            ),
        ),
    ]
