# Generated by Django 4.2 on 2023-05-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="slug",
            field=models.SlugField(
                blank=True, default=None, max_length=255, null=True, unique=True
            ),
        ),
    ]
