# Generated by Django 4.2 on 2023-05-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="school_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="School Name",
            ),
        ),
    ]
