# Generated by Django 4.2 on 2023-05-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_school_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password2",
            field=models.CharField(
                default=None, max_length=128, null=True, verbose_name="Confirm Password"
            ),
        ),
    ]
