# Generated by Django 4.2 on 2023-05-14 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "name",
                    models.CharField(
                        default="",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cities",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "name",
                    models.CharField(
                        default="",
                        max_length=5000,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Country",
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "name",
                    models.CharField(
                        default="",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="schools.country",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "State",
            },
        ),
        migrations.CreateModel(
            name="Schools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255, unique=True)),
                ("address", models.CharField(default="", max_length=255)),
                ("phone", models.CharField(default="", max_length=255)),
                ("email", models.EmailField(default="", max_length=255)),
                (
                    "pob",
                    models.CharField(default="", max_length=255, verbose_name="P.O.B"),
                ),
                ("date_established", models.DateField(verbose_name="Date Established")),
                (
                    "website",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="schools/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(default="", max_length=255)),
                (
                    "city",
                    models.ForeignKey(
                        default="",
                        max_length=255,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="schools.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        default="",
                        max_length=255,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="schools.country",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        default="",
                        max_length=255,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="schools.state",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Schools",
            },
        ),
        migrations.AddField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="schools.state",
            ),
        ),
    ]
