# Generated by Django 4.2 on 2023-05-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schools",
            options={"verbose_name_plural": "Schools"},
        ),
    ]
