# Generated by Django 4.2 on 2023-05-21 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="domain",
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="school",
            name="state",
            field=models.ForeignKey(
                default=None,
                max_length=255,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="schools.state",
            ),
        ),
    ]
