# Generated by Django 4.2 on 2023-05-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.CharField(
                default="",
                max_length=5000,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
