# Generated by Django 4.2 on 2023-05-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="pob",
            field=models.CharField(default="", max_length=255, verbose_name="P.O.Box"),
        ),
    ]
