# Generated by Django 4.2 on 2023-05-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_school_domain_alter_school_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="fd",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
