# Generated by Django 4.2 on 2023-05-13 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_schools_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="schools",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="schools",
            name="city",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="schools",
            name="country",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="schools",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schools",
            name="description",
            field=models.TextField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="schools",
            name="email",
            field=models.EmailField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="schools",
            name="logo",
            field=models.ImageField(default="", upload_to="schools/"),
        ),
        migrations.AddField(
            model_name="schools",
            name="phone",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="schools",
            name="pob",
            field=models.CharField(default="", max_length=255, verbose_name="P.O.B"),
        ),
        migrations.AddField(
            model_name="schools",
            name="state",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="schools",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="schools",
            name="website",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="schools",
            name="year_established",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
