# Generated by Django 4.2 on 2023-05-21 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_school_fd"),
    ]

    operations = [
        migrations.RenameField(
            model_name="school",
            old_name="fd",
            new_name="abbr",
        ),
    ]
