# Generated by Django 4.2 on 2023-05-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_alter_state_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schools",
            name="city",
        ),
        migrations.DeleteModel(
            name="City",
        ),
    ]
