# Generated by Django 4.2 on 2023-05-13 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_schools_address_schools_city_schools_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schools",
            name="year_established",
        ),
        migrations.AddField(
            model_name="schools",
            name="date_established",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date Established"
            ),
        ),
    ]
