# Generated by Django 4.2 on 2023-05-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0005_remove_schools_year_established_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schools",
            name="date_established",
            field=models.DateField(verbose_name="Date Established"),
        ),
    ]
