# Generated by Django 4.2 on 2023-05-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0006_alter_schools_date_established"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schools",
            name="logo",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="schools/"
            ),
        ),
        migrations.AlterField(
            model_name="schools",
            name="website",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
