# Generated by Django 4.2 on 2023-05-13 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0009_country_state_city"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name_plural": "Cities"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Country"},
        ),
        migrations.AlterModelOptions(
            name="state",
            options={"verbose_name_plural": "State"},
        ),
        migrations.AlterField(
            model_name="schools",
            name="city",
            field=models.ForeignKey(
                default="",
                max_length=255,
                on_delete=django.db.models.deletion.PROTECT,
                to="schools.city",
            ),
        ),
        migrations.AlterField(
            model_name="schools",
            name="country",
            field=models.ForeignKey(
                default="",
                max_length=255,
                on_delete=django.db.models.deletion.PROTECT,
                to="schools.country",
            ),
        ),
        migrations.AlterField(
            model_name="schools",
            name="state",
            field=models.ForeignKey(
                default="",
                max_length=255,
                on_delete=django.db.models.deletion.PROTECT,
                to="schools.state",
            ),
        ),
    ]
